name: ChatColor
author: i_Jedi
website: https://www.twitter.com/iJediPVP
main: me.i_Jedi.ChatColor.Main
version: 1.0.4
commands:
   CHAT:
      description: Display chat option menu.
      usage: /chat
   MSG:
      description: Send a private message to someone.
      usage: /msg <player> <message>
   TELL:
      description: Same as /msg.
      usage: /tell <player> <message>
   R:
      description: Reply to the last person that you messaged.
      usage: /r <message>